// Mock product data - will be replaced with CMS data later
export interface Product {
    id: number;
    name: string;
    nameMr: string;
    description: string;
    descriptionMr: string;
    price: number;
    category: 'cakes' | 'breads' | 'pastries' | 'cookies' | 'savory';
    image: string;
    featured: boolean;
}

export const products: Product[] = [
    // Cakes
    {
        id: 1,
        name: 'Chocolate Cake',
        nameMr: 'चॉकलेट केक',
        description: 'Rich, moist chocolate cake with chocolate frosting',
        descriptionMr: 'समृद्ध, ओलसर चॉकलेट केक चॉकलेट फ्रॉस्टिंगसह',
        price: 350,
        category: 'cakes',
        image: '/images/chocolate-cake.jpg',
        featured: true,
    },
    {
        id: 2,
        name: 'Vanilla Cake',
        nameMr: 'व्हॅनिला केक',
        description: 'Classic vanilla sponge cake with buttercream',
        descriptionMr: 'बटरक्रीमसह क्लासिक व्हॅनिला स्पंज केक',
        price: 300,
        category: 'cakes',
        image: '/images/vanilla-cake.jpg',
        featured: false,
    },
    {
        id: 3,
        name: 'Black Forest Cake',
        nameMr: 'ब्लॅक फॉरेस्ट केक',
        description: 'Chocolate cake with cherries and whipped cream',
        descriptionMr: 'चेरी आणि व्हीप्ड क्रीमसह चॉकलेट केक',
        price: 400,
        category: 'cakes',
        image: '/images/black-forest.jpg',
        featured: true,
    },
    {
        id: 4,
        name: 'Strawberry Cake',
        nameMr: 'स्ट्रॉबेरी केक',
        description: 'Fresh strawberry cake with cream filling',
        descriptionMr: 'क्रीम फिलिंगसह ताजी स्ट्रॉबेरी केक',
        price: 380,
        category: 'cakes',
        image: '/images/strawberry-cake.jpg',
        featured: false,
    },

    // Breads
    {
        id: 5,
        name: 'Multigrain Bread',
        nameMr: 'मल्टीग्रेन ब्रेड',
        description: 'Healthy multigrain bread loaf',
        descriptionMr: 'निरोगी मल्टीग्रेन ब्रेड लोफ',
        price: 40,
        category: 'breads',
        image: '/images/multigrain-bread.jpg',
        featured: true,
    },
    {
        id: 6,
        name: 'White Bread',
        nameMr: 'व्हाईट ब्रेड',
        description: 'Soft and fluffy white bread',
        descriptionMr: 'मऊ आणि फ्लफी व्हाईट ब्रेड',
        price: 35,
        category: 'breads',
        image: '/images/white-bread.jpg',
        featured: false,
    },
    {
        id: 7,
        name: 'Garlic Bread',
        nameMr: 'गार्लिक ब्रेड',
        description: 'Crispy garlic bread with herbs',
        descriptionMr: 'हर्ब्ससह कुरकुरीत गार्लिक ब्रेड',
        price: 60,
        category: 'breads',
        image: '/images/garlic-bread.jpg',
        featured: false,
    },
    {
        id: 8,
        name: 'Pav Bread',
        nameMr: 'पाव ब्रेड',
        description: 'Traditional Indian dinner rolls',
        descriptionMr: 'पारंपारिक भारतीय डिनर रोल्स',
        price: 30,
        category: 'breads',
        image: '/images/pav.jpg',
        featured: true,
    },

    // Pastries
    {
        id: 9,
        name: 'Pineapple Pastry',
        nameMr: 'पाइनॲपल पेस्ट्री',
        description: 'Sweet pineapple pastry with cream',
        descriptionMr: 'क्रीमसह गोड पाइनॲपल पेस्ट्री',
        price: 80,
        category: 'pastries',
        image: '/images/pineapple-pastry.jpg',
        featured: true,
    },
    {
        id: 10,
        name: 'Chocolate Pastry',
        nameMr: 'चॉकलेट पेस्ट्री',
        description: 'Rich chocolate pastry with ganache',
        descriptionMr: 'गॅनाशसह समृद्ध चॉकलेट पेस्ट्री',
        price: 90,
        category: 'pastries',
        image: '/images/chocolate-pastry.jpg',
        featured: false,
    },
    {
        id: 11,
        name: 'Butterscotch Pastry',
        nameMr: 'बटरस्कॉच पेस्ट्री',
        description: 'Butterscotch flavored pastry',
        descriptionMr: 'बटरस्कॉच फ्लेवर्ड पेस्ट्री',
        price: 85,
        category: 'pastries',
        image: '/images/butterscotch-pastry.jpg',
        featured: false,
    },
    {
        id: 12,
        name: 'Fruit Pastry',
        nameMr: 'फ्रूट पेस्ट्री',
        description: 'Fresh fruit topped pastry',
        descriptionMr: 'ताज्या फळांसह टॉप केलेली पेस्ट्री',
        price: 95,
        category: 'pastries',
        image: '/images/fruit-pastry.jpg',
        featured: true,
    },

    // Cookies
    {
        id: 13,
        name: 'Chocolate Chip Cookies',
        nameMr: 'चॉकलेट चिप कुकीज',
        description: 'Classic chocolate chip cookies (6 pcs)',
        descriptionMr: 'क्लासिक चॉकलेट चिप कुकीज (६ पीस)',
        price: 150,
        category: 'cookies',
        image: '/images/choco-chip-cookies.jpg',
        featured: true,
    },
    {
        id: 14,
        name: 'Butter Cookies',
        nameMr: 'बटर कुकीज',
        description: 'Crispy butter cookies (6 pcs)',
        descriptionMr: 'कुरकुरीत बटर कुकीज (६ पीस)',
        price: 120,
        category: 'cookies',
        image: '/images/butter-cookies.jpg',
        featured: false,
    },
    {
        id: 15,
        name: 'Oatmeal Cookies',
        nameMr: 'ओटमील कुकीज',
        description: 'Healthy oatmeal cookies (6 pcs)',
        descriptionMr: 'निरोगी ओटमील कुकीज (६ पीस)',
        price: 140,
        category: 'cookies',
        image: '/images/oatmeal-cookies.jpg',
        featured: false,
    },

    // Savory
    {
        id: 16,
        name: 'Veg Puff',
        nameMr: 'वेज पफ',
        description: 'Flaky puff pastry with vegetable filling',
        descriptionMr: 'भाजी फिलिंगसह फ्लेकी पफ पेस्ट्री',
        price: 25,
        category: 'savory',
        image: '/images/veg-puff.jpg',
        featured: true,
    },
    {
        id: 17,
        name: 'Cheese Pizza',
        nameMr: 'चीज पिझ्झा',
        description: 'Delicious cheese pizza slice',
        descriptionMr: 'स्वादिष्ट चीज पिझ्झा स्लाइस',
        price: 50,
        category: 'savory',
        image: '/images/cheese-pizza.jpg',
        featured: false,
    },
    {
        id: 18,
        name: 'Sandwich',
        nameMr: 'सँडविच',
        description: 'Fresh vegetable sandwich',
        descriptionMr: 'ताजी भाजी सँडविच',
        price: 40,
        category: 'savory',
        image: '/images/sandwich.jpg',
        featured: false,
    },
    {
        id: 19,
        name: 'Samosa',
        nameMr: 'समोसा',
        description: 'Crispy fried samosa (2 pcs)',
        descriptionMr: 'कुरकुरीत तळलेला समोसा (२ पीस)',
        price: 20,
        category: 'savory',
        image: '/images/samosa.jpg',
        featured: true,
    },
    {
        id: 20,
        name: 'Paneer Roll',
        nameMr: 'पनीर रोल',
        description: 'Spicy paneer wrap roll',
        descriptionMr: 'मसालेदार पनीर रॅप रोल',
        price: 55,
        category: 'savory',
        image: '/images/paneer-roll.jpg',
        featured: false,
    },
];

export const categories = [
    { id: 'all', name: 'All', nameMr: 'सर्व' },
    { id: 'cakes', name: 'Cakes', nameMr: 'केक' },
    { id: 'breads', name: 'Breads', nameMr: 'ब्रेड' },
    { id: 'pastries', name: 'Pastries', nameMr: 'पेस्ट्री' },
    { id: 'cookies', name: 'Cookies', nameMr: 'कुकीज' },
    { id: 'savory', name: 'Savory', nameMr: 'चवदार' },
];
