// Mock product data - will be replaced with CMS data later
export interface Product {
    id: number;
    name: string;
    nameMr: string;
    description: string;
    descriptionMr: string;
    price: number;
    category: 'cakes' | 'breads' | 'biscuits' | 'khari' | 'sweets';
    image: string;
    featured: boolean;
}

export const products: Product[] = [
    // Savory Items (नमकीन/खारी)
    {
        id: 1,
        name: 'Nargees Khari',
        nameMr: 'नर्गिस खारी',
        description: 'Crispy layered savory khari with spices',
        descriptionMr: 'मसालेदार कुरकुरीत लेयर्ड खारी',
        price: 25,
        category: 'khari',
        image: '/images/nargees-khari.jpg',
        featured: true,
    },
    {
        id: 2,
        name: 'Patti Khari',
        nameMr: 'पट्टी खारी',
        description: 'Strip-style crispy savory khari',
        descriptionMr: 'पट्टी स्टाइल कुरकुरीत खारी',
        price: 20,
        category: 'khari',
        image: '/images/patti-khari.jpg',
        featured: false,
    },
    {
        id: 3,
        name: 'Samosa Khari',
        nameMr: 'समोसा खारी',
        description: 'Samosa-shaped savory khari',
        descriptionMr: 'समोसा आकाराचे खारी',
        price: 30,
        category: 'khari',
        image: '/images/samosa-khari.jpg',
        featured: true,
    },
    {
        id: 4,
        name: 'Ajwain Biscuit',
        nameMr: 'अजवाइन बिस्कीट',
        description: 'Crunchy biscuits flavored with carom seeds',
        descriptionMr: 'अजवाइन फ्लेवरचे कुरकुरीत बिस्कीट',
        price: 35,
        category: 'biscuits',
        image: '/images/ajwain-biscuit.jpg',
        featured: true,
    },

    // Breads
    {
        id: 5,
        name: 'Kaju Biscuit',
        nameMr: 'काजू बिस्कीट',
        description: 'Rich cashew-flavored biscuits',
        descriptionMr: 'काजू फ्लेवरचे बिस्कीट',
        price: 50,
        category: 'biscuits',
        image: '/images/kaju-biscuit.jpg',
        featured: true,
    },
    {
        id: 6,
        name: 'Jam Biscuit',
        nameMr: 'जॅम बिस्कीट',
        description: 'Sweet biscuits with jam filling',
        descriptionMr: 'जॅम फिलिंगसह गोड बिस्कीट',
        price: 40,
        category: 'biscuits',
        image: '/images/jam-biscuit.jpg',
        featured: false,
    },
    {
        id: 7,
        name: 'Milk Biscuit',
        nameMr: 'मिल्क बिस्कीट',
        description: 'Soft milk-flavored biscuits',
        descriptionMr: 'मऊ मिल्क फ्लेवरचे बिस्कीट',
        price: 30,
        category: 'biscuits',
        image: '/images/milk-biscuit.jpg',
        featured: false,
    },
    {
        id: 8,
        name: 'Milk Bread',
        nameMr: 'मिल्क ब्रेड',
        description: 'Soft and fluffy milk bread loaf',
        descriptionMr: 'मऊ आणि फ्लफी मिल्क ब्रेड लोफ',
        price: 40,
        category: 'breads',
        image: '/images/milk-bread.jpg',
        featured: true,
    },
    {
        id: 10,
        name: 'Jeera Butter',
        nameMr: 'जीरा बटर खारी',
        description: 'Cumin-flavored butter delight',
        descriptionMr: 'जीरा फ्लेवरचे बटर डिलाइट खारी',
        price: 65,
        category: 'khari',
        image: '/images/jeera-butter.jpg',
        featured: false,
    },
    {
        id: 11,
        name: 'Ajwain Butter',
        nameMr: 'अजवाइन बटर खारी',
        description: 'Carom seed flavored butter khari',
        descriptionMr: 'अजवाइन फ्लेवर केलेली बटर खारी',
        price: 65,
        category: 'khari',
        image: '/images/ajwain-butter.jpg',
        featured: false,
    },
    // Sweet Items
    {
        id: 12,
        name: 'Nankat',
        nameMr: 'नानकेट',
        description: 'Traditional sweet biscuits',
        descriptionMr: 'पारंपरिक गोड बिस्कीट',
        price: 80,
        category: 'sweets',
        image: '/images/nankat.jpg',
        featured: true,
    },

    // Cookies
    {
        id: 13,
        name: 'Cream Roll',
        nameMr: 'क्रीम रोल',
        description: 'Delicious cream-filled rolls',
        descriptionMr: 'स्वादिष्ट क्रीम भरलेले रोल्स',
        price: 45,
        category: 'sweets',
        image: '/images/cream-roll.jpg',
        featured: true,
    },
    // Savory Items (continued)
    {
        id: 14,
        name: 'Chocolate Biscuit',
        nameMr: 'चॉकलेट बिस्कीट',
        description: 'Rich chocolate flavored biscuits',
        descriptionMr: 'समृद्ध चॉकलेट फ्लेवरचे बिस्कीट',
        price: 40,
        category: 'biscuits',
        image: '/images/chocolate-biscuit.jpg',
        featured: false,
    },
    {
        id: 15,
        name: 'Sujberry Biscuit',
        nameMr: 'सुजबेरी बिस्कीट',
        description: 'Delightful sujberry flavored biscuits',
        descriptionMr: 'आनंददायक सुजबेरी फ्लेवरचे बिस्कीट',
        price: 35,
        category: 'biscuits',
        image: '/images/sujberry-biscuit.jpg',
        featured: false,
    },
    {
        id: 16,
        name: 'Kaju Badam Biscuit',
        nameMr: 'काजु बदाम बिस्कीट',
        description: 'Premium cashew and almond biscuits',
        descriptionMr: 'प्रीमियम काजू आणि बदाम बिस्कीट',
        price: 60,
        category: 'biscuits',
        image: '/images/kaju-badam-biscuit.jpg',
        featured: true,
    },
    {
        id: 17,
        name: 'Mix Biscuit',
        nameMr: 'मिक्स बिस्कीट',
        description: 'Assorted mix of delicious biscuits',
        descriptionMr: 'स्वादिष्ट बिस्कीटचे मिश्रण',
        price: 45,
        category: 'biscuits',
        image: '/images/mix-biscuit.jpg',
        featured: false,
    },
    {
        id: 18,
        name: 'Khobara Jam Biscuit',
        nameMr: 'खोबरा जाम बिस्कीट',
        description: 'Coconut jam filled biscuits',
        descriptionMr: 'नारळ जॅम भरलेले बिस्कीट',
        price: 45,
        category: 'biscuits',
        image: '/images/khobara-jam-biscuit.jpg',
        featured: false,
    },
    {
        id: 19,
        name: 'Maska Butter',
        nameMr: 'मसका बटर',
        description: 'Traditional butter flavored khari',
        descriptionMr: 'पारंपरिक बटर फ्लेवर केलेली खारी',
        price: 70,
        category: 'khari',
        image: '/images/maska-butter.jpg',
        featured: false,
    },
    // Cakes (Popular items)
    {
        id: 20,
        name: 'Chocolate Cake',
        nameMr: 'चॉकलेट केक',
        description: 'Rich, moist chocolate cake with chocolate frosting',
        descriptionMr: 'समृद्ध, ओलसर चॉकलेट केक चॉकलेट फ्रॉस्टिंगसह',
        price: 350,
        category: 'cakes',
        image: '/images/chocolate-cake.jpg',
        featured: true,
    },
    {
        id: 21,
        name: 'Vanilla Cake',
        nameMr: 'व्हॅनिला केक',
        description: 'Classic vanilla sponge cake with buttercream',
        descriptionMr: 'बटरक्रीमसह क्लासिक व्हॅनिला स्पंज केक',
        price: 300,
        category: 'cakes',
        image: '/images/vanilla-cake.jpg',
        featured: false,
    },
    {
        id: 22,
        name: 'Black Forest Cake',
        nameMr: 'ब्लॅक फॉरेस्ट केक',
        description: 'Chocolate cake with cherries and whipped cream',
        descriptionMr: 'चेरी आणि व्हीप्ड क्रीमसह चॉकलेट केक',
        price: 400,
        category: 'cakes',
        image: '/images/black-forest.jpg',
        featured: false,
    },
    {
        id: 23,
        name: 'Strawberry Cake',
        nameMr: 'स्ट्रॉबेरी केक',
        description: 'Fresh strawberry cake with cream filling',
        descriptionMr: 'क्रीम फिलिंगसह ताजी स्ट्रॉबेरी केक',
        price: 380,
        category: 'cakes',
        image: '/images/strawberry-cake.jpg',
        featured: false,
    },
];

export const categories = [
    { id: 'all', name: 'All', nameMr: 'सर्व' },
    { id: 'cakes', name: 'Cakes', nameMr: 'केक' },
    { id: 'breads', name: 'Breads', nameMr: 'ब्रेड' },
    { id: 'biscuits', name: 'Biscuits', nameMr: 'बिस्कीट' },
    { id: 'khari', name: 'Khari', nameMr: 'खारी' },
    { id: 'sweets', name: 'Sweets', nameMr: 'मिठाई' },
];
